### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by HakkaTjakka** [SakuraTao2007/ReplayMod#1]
would it be if the thing works.......

It reminds me of Microsoft Windows......
Lots of blah blah blah, but in the end => CRASH

**Comment by mkwwmka5** [comment]
hello，nice to see you~
Are you the maker of Replaymod
If yes, please tell me, thank you


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mkwwmka5/ReplayMod"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月17日(星期五) 晚上7:22
收件人:&nbsp;"mkwwmka5/ReplayMod"<ReplayMod@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[mkwwmka5/ReplayMod] Nice (#1)





 
would it be if the thing works.......
 
It reminds me of Microsoft Windows......
 Lots of blah blah blah, but in the end =&gt; CRASH

**Comment by HakkaTjakka** [comment]
No.
This is me:
https://www.facebook.com/Minecraft-Worldeditor-110607880303634/
https://github.com/HakkaTjakka

Sorry for the late response...
